// Generated by purs version 0.13.5
"use strict";
var Egg_Logic_CreatePlayers = require("../Egg.Logic.CreatePlayers/index.js");
var Egg_Types_GameState = require("../Egg.Types.GameState/index.js");
var initialiseGameState = function (board) {
    var initialGameState = Egg_Types_GameState.createGameState(board);
    return {
        players: Egg_Logic_CreatePlayers.getPlayersFromBoard(board),
        board: initialGameState.board,
        score: initialGameState.score,
        rotations: initialGameState.rotations,
        rotateAngle: initialGameState.rotateAngle,
        renderAngle: initialGameState.renderAngle,
        outcome: initialGameState.outcome,
        turns: initialGameState.turns,
        current: initialGameState.current,
        screenSize: initialGameState.screenSize
    };
};
module.exports = {
    initialiseGameState: initialiseGameState
};
