// Generated by purs version 0.13.5
"use strict";
var ComonadTrans = function (lower) {
    this.lower = lower;
};
var lower = function (dict) {
    return dict.lower;
};
module.exports = {
    lower: lower,
    ComonadTrans: ComonadTrans
};
