// Generated by purs version 0.13.5
"use strict";
var Data_Eq = require("../Data.Eq/index.js");
var Data_Ord = require("../Data.Ord/index.js");
var Data_Ordering = require("../Data.Ordering/index.js");
var Data_Show = require("../Data.Show/index.js");
var ScreenSize = (function () {
    function ScreenSize(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    ScreenSize.create = function (value0) {
        return function (value1) {
            return new ScreenSize(value0, value1);
        };
    };
    return ScreenSize;
})();
var showScreenSize = new Data_Show.Show(function (v) {
    return "ScreenSize " + (Data_Show.show(Data_Show.showInt)(v.value0) + (", " + Data_Show.show(Data_Show.showInt)(v.value1)));
});
var screenSize = function (x) {
    return function (y) {
        return new ScreenSize(Data_Ord.max(Data_Ord.ordInt)(x)(1), Data_Ord.max(Data_Ord.ordInt)(y)(1));
    };
};
var getWidth = function (v) {
    return v.value0;
};
var getHeight = function (v) {
    return v.value1;
};
var smallest = function (s) {
    return Data_Ord.min(Data_Ord.ordInt)(getWidth(s))(getHeight(s));
};
var eqScreenSize = new Data_Eq.Eq(function (x) {
    return function (y) {
        return x.value0 === y.value0 && x.value1 === y.value1;
    };
});
var ordScreenSize = new Data_Ord.Ord(function () {
    return eqScreenSize;
}, function (x) {
    return function (y) {
        var v = Data_Ord.compare(Data_Ord.ordInt)(x.value0)(y.value0);
        if (v instanceof Data_Ordering.LT) {
            return Data_Ordering.LT.value;
        };
        if (v instanceof Data_Ordering.GT) {
            return Data_Ordering.GT.value;
        };
        return Data_Ord.compare(Data_Ord.ordInt)(x.value1)(y.value1);
    };
});
module.exports = {
    screenSize: screenSize,
    getWidth: getWidth,
    getHeight: getHeight,
    smallest: smallest,
    ScreenSize: ScreenSize,
    eqScreenSize: eqScreenSize,
    ordScreenSize: ordScreenSize,
    showScreenSize: showScreenSize
};
