// Generated by purs version 0.13.5
"use strict";
var Data_Maybe = require("../Data.Maybe/index.js");
var Egg_Types_Coord = require("../Egg.Types.Coord/index.js");
var Egg_Types_CurrentFrame = require("../Egg.Types.CurrentFrame/index.js");
var Egg_Types_PlayerType = require("../Egg.Types.PlayerType/index.js");
var defaultPlayer = {
    coords: Egg_Types_Coord.createCoord(0)(0),
    currentFrame: Egg_Types_CurrentFrame.createCurrentFrame(1),
    direction: Egg_Types_Coord.createCoord(1)(0),
    falling: false,
    id: 0,
    lastAction: Data_Maybe.Nothing.value,
    moved: false,
    oldDirection: Egg_Types_Coord.createCoord(0)(0),
    stop: false,
    playerType: Egg_Types_PlayerType.defaultPlayerType
};
module.exports = {
    defaultPlayer: defaultPlayer
};
