// Generated by purs version 0.13.5
"use strict";
var Data_Eq = require("../Data.Eq/index.js");
var Data_Ord = require("../Data.Ord/index.js");
var Data_Ordering = require("../Data.Ordering/index.js");
var Data_Show = require("../Data.Show/index.js");
var Clockwise = (function () {
    function Clockwise() {

    };
    Clockwise.value = new Clockwise();
    return Clockwise;
})();
var AntiClockwise = (function () {
    function AntiClockwise() {

    };
    AntiClockwise.value = new AntiClockwise();
    return AntiClockwise;
})();
var showClockwise = new Data_Show.Show(function (v) {
    if (v instanceof Clockwise) {
        return "Clockwise";
    };
    if (v instanceof AntiClockwise) {
        return "AntiClockwise";
    };
    throw new Error("Failed pattern match at Egg.Types.Clockwise (line 14, column 1 - line 16, column 39): " + [ v.constructor.name ]);
});
var eqClockwise = new Data_Eq.Eq(function (x) {
    return function (y) {
        if (x instanceof Clockwise && y instanceof Clockwise) {
            return true;
        };
        if (x instanceof AntiClockwise && y instanceof AntiClockwise) {
            return true;
        };
        return false;
    };
});
var ordClockwise = new Data_Ord.Ord(function () {
    return eqClockwise;
}, function (x) {
    return function (y) {
        if (x instanceof Clockwise && y instanceof Clockwise) {
            return Data_Ordering.EQ.value;
        };
        if (x instanceof Clockwise) {
            return Data_Ordering.LT.value;
        };
        if (y instanceof Clockwise) {
            return Data_Ordering.GT.value;
        };
        if (x instanceof AntiClockwise && y instanceof AntiClockwise) {
            return Data_Ordering.EQ.value;
        };
        throw new Error("Failed pattern match at Egg.Types.Clockwise (line 12, column 1 - line 12, column 46): " + [ x.constructor.name, y.constructor.name ]);
    };
});
module.exports = {
    Clockwise: Clockwise,
    AntiClockwise: AntiClockwise,
    eqClockwise: eqClockwise,
    ordClockwise: ordClockwise,
    showClockwise: showClockwise
};
