// Generated by purs version 0.13.5
"use strict";
var Affjax = require("../Affjax/index.js");
var Affjax_ResponseFormat = require("../Affjax.ResponseFormat/index.js");
var Control_Applicative = require("../Control.Applicative/index.js");
var Control_Bind = require("../Control.Bind/index.js");
var Data_Either = require("../Data.Either/index.js");
var Data_HTTP_Method = require("../Data.HTTP.Method/index.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var Data_Show = require("../Data.Show/index.js");
var Effect_Aff = require("../Effect.Aff/index.js");
var Egg_Logic_LoadLevel = require("../Egg.Logic.LoadLevel/index.js");
var Egg_Types_ResourceUrl = require("../Egg.Types.ResourceUrl/index.js");
var levelLoader = function (resource) {
    var settings = {
        url: Data_Show.show(Egg_Types_ResourceUrl.showResourceUrl)(resource),
        method: new Data_Either.Left(Data_HTTP_Method.GET.value),
        responseFormat: Affjax_ResponseFormat.string,
        content: Affjax.defaultRequest.content,
        headers: Affjax.defaultRequest.headers,
        password: Affjax.defaultRequest.password,
        username: Affjax.defaultRequest.username,
        withCredentials: Affjax.defaultRequest.withCredentials
    };
    return Control_Bind.bind(Effect_Aff.bindAff)(Affjax.request(settings))(function (v) {
        return Control_Applicative.pure(Effect_Aff.applicativeAff)(Data_Either.hush(v.body));
    });
};
var loadLevel = function (i) {
    return Control_Bind.bind(Effect_Aff.bindAff)(levelLoader(new Egg_Types_ResourceUrl.LevelResource(i)))(function (v) {
        var level = Control_Bind.bind(Data_Maybe.bindMaybe)(v)(Egg_Logic_LoadLevel.readLevel);
        return Control_Applicative.pure(Effect_Aff.applicativeAff)(level);
    });
};
module.exports = {
    levelLoader: levelLoader,
    loadLevel: loadLevel
};
