// Generated by purs version 0.13.5
"use strict";
var Data_EuclideanRing = require("../Data.EuclideanRing/index.js");
var Data_Int = require("../Data.Int/index.js");
var Graphics_Canvas = require("../Graphics.Canvas/index.js");
var background = function (size) {
    return {
        x0: Data_Int.toNumber(Data_EuclideanRing.div(Data_EuclideanRing.euclideanRingInt)(size)(2)),
        y0: 0.0,
        x1: Data_Int.toNumber(Data_EuclideanRing.div(Data_EuclideanRing.euclideanRingInt)(size)(2)),
        y1: Data_Int.toNumber(size)
    };
};
var getGradient = function (size) {
    return function (context) {
        return function __do() {
            var v = Graphics_Canvas.createLinearGradient(context)(background(size))();
            Graphics_Canvas.addColorStop(v)(1.0)("#152b26")();
            Graphics_Canvas.addColorStop(v)(0.8)("#102029")();
            Graphics_Canvas.addColorStop(v)(0.6)("#192b34")();
            Graphics_Canvas.addColorStop(v)(0.0)("#dd8888")();
            return v;
        };
    };
};
module.exports = {
    background: background,
    getGradient: getGradient
};
