// Generated by purs version 0.13.5
"use strict";
var Data_Foldable = require("../Data.Foldable/index.js");
var Data_Functor = require("../Data.Functor/index.js");
var Data_List = require("../Data.List/index.js");
var Data_Map_Internal = require("../Data.Map.Internal/index.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var Data_Tuple = require("../Data.Tuple/index.js");
var Egg_Types_PlayerType = require("../Egg.Types.PlayerType/index.js");
var Egg_Types_ResourceUrl = require("../Egg.Types.ResourceUrl/index.js");
var playerTypes = Data_Map_Internal.fromFoldable(Egg_Types_PlayerType.ordPlayerKind)(Data_Foldable.foldableArray)([ new Data_Tuple.Tuple(Egg_Types_PlayerType.Egg.value, {
    frames: 18,
    img: new Egg_Types_ResourceUrl.SpriteResource("egg-sprite"),
    multiplier: 1,
    title: "It is of course the egg",
    type_: Egg_Types_PlayerType.Egg.value,
    fallSpeed: Egg_Types_PlayerType.defaultPlayerType.fallSpeed,
    flying: Egg_Types_PlayerType.defaultPlayerType.flying,
    movePattern: Egg_Types_PlayerType.defaultPlayerType.movePattern,
    moveSpeed: Egg_Types_PlayerType.defaultPlayerType.moveSpeed
}), new Data_Tuple.Tuple(Egg_Types_PlayerType.RedEgg.value, {
    frames: 18,
    img: new Egg_Types_ResourceUrl.SpriteResource("egg-sprite-red"),
    multiplier: 2,
    title: "It is of course the red egg",
    type_: Egg_Types_PlayerType.RedEgg.value,
    fallSpeed: Egg_Types_PlayerType.defaultPlayerType.fallSpeed,
    flying: Egg_Types_PlayerType.defaultPlayerType.flying,
    movePattern: Egg_Types_PlayerType.defaultPlayerType.movePattern,
    moveSpeed: Egg_Types_PlayerType.defaultPlayerType.moveSpeed
}), new Data_Tuple.Tuple(Egg_Types_PlayerType.BlueEgg.value, {
    frames: 18,
    img: new Egg_Types_ResourceUrl.SpriteResource("egg-sprite-blue"),
    multiplier: 5,
    title: "It is of course the blue egg",
    type_: Egg_Types_PlayerType.BlueEgg.value,
    fallSpeed: Egg_Types_PlayerType.defaultPlayerType.fallSpeed,
    flying: Egg_Types_PlayerType.defaultPlayerType.flying,
    movePattern: Egg_Types_PlayerType.defaultPlayerType.movePattern,
    moveSpeed: Egg_Types_PlayerType.defaultPlayerType.moveSpeed
}), new Data_Tuple.Tuple(Egg_Types_PlayerType.YellowEgg.value, {
    frames: 18,
    img: new Egg_Types_ResourceUrl.SpriteResource("egg-sprite-yellow"),
    multiplier: 10,
    title: "It is of course the yellow egg",
    type_: Egg_Types_PlayerType.YellowEgg.value,
    fallSpeed: Egg_Types_PlayerType.defaultPlayerType.fallSpeed,
    flying: Egg_Types_PlayerType.defaultPlayerType.flying,
    movePattern: Egg_Types_PlayerType.defaultPlayerType.movePattern,
    moveSpeed: Egg_Types_PlayerType.defaultPlayerType.moveSpeed
}), new Data_Tuple.Tuple(Egg_Types_PlayerType.RainbowEgg.value, {
    frames: 18,
    img: new Egg_Types_ResourceUrl.SpriteResource("egg-rainbow"),
    multiplier: 1,
    title: "It goes without saying that this is the rainbow egg",
    type_: Egg_Types_PlayerType.RainbowEgg.value,
    fallSpeed: Egg_Types_PlayerType.defaultPlayerType.fallSpeed,
    flying: Egg_Types_PlayerType.defaultPlayerType.flying,
    movePattern: Egg_Types_PlayerType.defaultPlayerType.movePattern,
    moveSpeed: Egg_Types_PlayerType.defaultPlayerType.moveSpeed
}), new Data_Tuple.Tuple(Egg_Types_PlayerType.SilverEgg.value, {
    fallSpeed: 20,
    frames: 1,
    img: new Egg_Types_ResourceUrl.SpriteResource("silver-egg"),
    moveSpeed: 0,
    multiplier: 10,
    title: "It is of course the silver egg",
    type_: Egg_Types_PlayerType.SilverEgg.value,
    flying: Egg_Types_PlayerType.defaultPlayerType.flying,
    movePattern: Egg_Types_PlayerType.defaultPlayerType.movePattern
}), new Data_Tuple.Tuple(Egg_Types_PlayerType.Blade.value, {
    frames: 18,
    img: new Egg_Types_ResourceUrl.SpriteResource("blade-sprite"),
    title: "It is the mean spirited blade",
    type_: Egg_Types_PlayerType.Blade.value,
    flying: true,
    fallSpeed: Egg_Types_PlayerType.defaultPlayerType.fallSpeed,
    movePattern: Egg_Types_PlayerType.defaultPlayerType.movePattern,
    moveSpeed: Egg_Types_PlayerType.defaultPlayerType.moveSpeed,
    multiplier: Egg_Types_PlayerType.defaultPlayerType.multiplier
}), new Data_Tuple.Tuple(Egg_Types_PlayerType.FindBlade.value, {
    frames: 18,
    img: new Egg_Types_ResourceUrl.SpriteResource("find-blade-sprite"),
    title: "It is the mean spirited blade",
    type_: Egg_Types_PlayerType.FindBlade.value,
    movePattern: "seek-egg",
    flying: true,
    fallSpeed: Egg_Types_PlayerType.defaultPlayerType.fallSpeed,
    moveSpeed: Egg_Types_PlayerType.defaultPlayerType.moveSpeed,
    multiplier: Egg_Types_PlayerType.defaultPlayerType.multiplier
}) ]);
var spriteResources = (function () {
    var sprites = Data_Functor.map(Data_Map_Internal.functorMap)(function (v) {
        return v.img;
    })(playerTypes);
    return Data_List.fromFoldable(Data_Map_Internal.foldableMap)(sprites);
})();
var getPlayerType = function (k) {
    return Data_Maybe.fromMaybe(Egg_Types_PlayerType.defaultPlayerType)(Data_Map_Internal.lookup(Egg_Types_PlayerType.ordPlayerKind)(k)(playerTypes));
};
module.exports = {
    spriteResources: spriteResources,
    getPlayerType: getPlayerType,
    playerTypes: playerTypes
};
