// Generated by purs version 0.13.5
"use strict";
var Egg_Types_Tile = require("../Egg.Types.Tile/index.js");
var Matrix = require("../Matrix/index.js");
var emptyBoard = function (size) {
    return Matrix.repeat(size)(size)(Egg_Types_Tile.emptyTile);
};
module.exports = {
    emptyBoard: emptyBoard
};
