// Generated by purs version 0.13.5
"use strict";
var Data_Eq = require("../Data.Eq/index.js");
var Data_Ord = require("../Data.Ord/index.js");
var Data_Ordering = require("../Data.Ordering/index.js");
var Data_Semigroup = require("../Data.Semigroup/index.js");
var Data_Show = require("../Data.Show/index.js");
var SmallCoord = (function () {
    function SmallCoord(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    SmallCoord.create = function (value0) {
        return function (value1) {
            return new SmallCoord(value0, value1);
        };
    };
    return SmallCoord;
})();
var toCoord = function (v) {
    return {
        x: v.value0,
        y: v.value1,
        offsetX: 0,
        offsetY: 0
    };
};
var showSmallCoord = new Data_Show.Show(function (v) {
    return "(" + (Data_Show.show(Data_Show.showInt)(v.value0) + (", " + (Data_Show.show(Data_Show.showInt)(v.value1) + ")")));
});
var semigroupSmallCoord = new Data_Semigroup.Semigroup(function (v) {
    return function (v1) {
        return new SmallCoord(v.value0 + v1.value0 | 0, v.value1 + v1.value1 | 0);
    };
});
var fromCoord = function (v) {
    return new SmallCoord(v.x, v.y);
};
var eqSmallCoord = new Data_Eq.Eq(function (x) {
    return function (y) {
        return x.value0 === y.value0 && x.value1 === y.value1;
    };
});
var ordSmallCoord = new Data_Ord.Ord(function () {
    return eqSmallCoord;
}, function (x) {
    return function (y) {
        var v = Data_Ord.compare(Data_Ord.ordInt)(x.value0)(y.value0);
        if (v instanceof Data_Ordering.LT) {
            return Data_Ordering.LT.value;
        };
        if (v instanceof Data_Ordering.GT) {
            return Data_Ordering.GT.value;
        };
        return Data_Ord.compare(Data_Ord.ordInt)(x.value1)(y.value1);
    };
});
module.exports = {
    SmallCoord: SmallCoord,
    fromCoord: fromCoord,
    toCoord: toCoord,
    eqSmallCoord: eqSmallCoord,
    ordSmallCoord: ordSmallCoord,
    showSmallCoord: showSmallCoord,
    semigroupSmallCoord: semigroupSmallCoord
};
