// Generated by purs version 0.13.5
"use strict";
var Data_EuclideanRing = require("../Data.EuclideanRing/index.js");
var Data_Int = require("../Data.Int/index.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var Egg_Types_Coord = require("../Egg.Types.Coord/index.js");
var Egg_Types_Tile = require("../Egg.Types.Tile/index.js");
var Matrix = require("../Matrix/index.js");
var replaceTile = function (board) {
    return function (v) {
        return function (tile) {
            var newBoard = Matrix.set(v.x)(v.y)(tile)(board);
            return Data_Maybe.fromMaybe(board)(newBoard);
        };
    };
};
var renderItemToCoord = function (v) {
    return Egg_Types_Coord.createCoord(v.x)(v.y);
};
var invertTranslation = function (trans) {
    return {
        translateX: -1.0 * trans.translateX,
        translateY: -1.0 * trans.translateY
    };
};
var getTileByCoord = function (board) {
    return function (v) {
        var y = Data_EuclideanRing.mod(Data_EuclideanRing.euclideanRingInt)(v.y)(Matrix.height(board));
        var x = Data_EuclideanRing.mod(Data_EuclideanRing.euclideanRingInt)(v.x)(Matrix.width(board));
        var tile = Matrix.get(x)(y)(board);
        return Data_Maybe.fromMaybe(Egg_Types_Tile.emptyTile)(tile);
    };
};
var createTileTranslation = function (c) {
    return {
        translateX: Data_Int.toNumber(Data_EuclideanRing.div(Data_EuclideanRing.euclideanRingInt)(Egg_Types_Tile.tileSize)(2) + Egg_Types_Coord.totalX(c) | 0),
        translateY: Data_Int.toNumber(Data_EuclideanRing.div(Data_EuclideanRing.euclideanRingInt)(Egg_Types_Tile.tileSize)(2) + Egg_Types_Coord.totalY(c) | 0)
    };
};
var createCenteredTranslation = function (i) {
    return {
        translateX: Data_Int.toNumber(Data_EuclideanRing.div(Data_EuclideanRing.euclideanRingInt)(i)(2)),
        translateY: Data_Int.toNumber(Data_EuclideanRing.div(Data_EuclideanRing.euclideanRingInt)(i)(2))
    };
};
var createBoardSize = function (i) {
    return {
        width: i,
        height: i
    };
};
var boardSizeFromBoard = function (board) {
    return {
        width: Matrix.width(board),
        height: Matrix.height(board)
    };
};
var boardFromArray = function (tiles) {
    return Data_Maybe.fromMaybe(Matrix.empty)(Matrix.fromArray(tiles));
};
module.exports = {
    createBoardSize: createBoardSize,
    invertTranslation: invertTranslation,
    createCenteredTranslation: createCenteredTranslation,
    createTileTranslation: createTileTranslation,
    getTileByCoord: getTileByCoord,
    replaceTile: replaceTile,
    boardFromArray: boardFromArray,
    renderItemToCoord: renderItemToCoord,
    boardSizeFromBoard: boardSizeFromBoard
};
