// Generated by purs version 0.13.5
"use strict";
var Control_Applicative = require("../Control.Applicative/index.js");
var Control_Bind = require("../Control.Bind/index.js");
var Data_Int = require("../Data.Int/index.js");
var Data_List_Types = require("../Data.List.Types/index.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var Data_Semigroup = require("../Data.Semigroup/index.js");
var Data_Unit = require("../Data.Unit/index.js");
var Effect_Aff = require("../Effect.Aff/index.js");
var Effect_Class = require("../Effect.Class/index.js");
var Effect_Random = require("../Effect.Random/index.js");
var Egg_Data_PlayerTypes = require("../Egg.Data.PlayerTypes/index.js");
var Egg_Data_TileSet = require("../Egg.Data.TileSet/index.js");
var Egg_Dom_AnimationLoop = require("../Egg.Dom.AnimationLoop/index.js");
var Egg_Dom_Canvas = require("../Egg.Dom.Canvas/index.js");
var Egg_Dom_Events = require("../Egg.Dom.Events/index.js");
var Egg_Dom_Loader = require("../Egg.Dom.Loader/index.js");
var Egg_Dom_Renderer = require("../Egg.Dom.Renderer/index.js");
var Egg_Logic_InitialiseLevel = require("../Egg.Logic.InitialiseLevel/index.js");
var Egg_Logic_TakeTurn = require("../Egg.Logic.TakeTurn/index.js");
var renderCallback = function (canvasData) {
    return function (old) {
        return function ($$new) {
            return Egg_Dom_Renderer.renderGameState(canvasData)(old)($$new);
        };
    };
};
var startNewLevel = function (canvas) {
    return Control_Bind.bind(Effect_Aff.bindAff)(Effect_Class.liftEffect(Effect_Aff.monadEffectAff)(Effect_Random.randomInt(1)(20)))(function (v) {
        return Control_Bind.bind(Effect_Aff.bindAff)(Egg_Dom_Loader.loadLevel(v))(function (v1) {
            if (v1 instanceof Data_Maybe.Just) {
                return Effect_Class.liftEffect(Effect_Aff.monadEffectAff)(start(canvas)(v1.value0));
            };
            return Control_Applicative.pure(Effect_Aff.applicativeAff)(Data_Unit.unit);
        });
    });
};
var start = function (canvas) {
    return function (level) {
        return function __do() {
            Egg_Dom_Canvas.sizeCanvas(canvas.buffer.element)(Data_Int.toNumber(level.boardSize.width) * 64.0)();
            Egg_Dom_Canvas.sizeCanvas(canvas.screen.element)(Data_Int.toNumber(level.boardSize.width) * 64.0)();
            var v = Egg_Dom_AnimationLoop.createBlankState(Egg_Logic_InitialiseLevel.initialiseGameState(level.board))();
            Egg_Dom_AnimationLoop.animationLoop(v)(Egg_Logic_TakeTurn.go)(renderCallback(canvas))(Effect_Aff.launchAff_(startNewLevel(canvas)))();
            return Egg_Dom_Events.setupEvents(v.inputEvent)();
        };
    };
};
var imageResources = Data_Semigroup.append(Data_List_Types.semigroupList)(Egg_Data_TileSet.tileResources)(Egg_Data_PlayerTypes.spriteResources);
var setupGame = Control_Bind.bind(Effect_Aff.bindAff)(Egg_Dom_Canvas.setupCanvas(imageResources))(startNewLevel);
var main = Effect_Aff.launchAff_(setupGame);
module.exports = {
    main: main,
    setupGame: setupGame,
    startNewLevel: startNewLevel,
    start: start,
    renderCallback: renderCallback,
    imageResources: imageResources
};
