// Generated by purs version 0.13.5
"use strict";
var Control_Applicative = require("../Control.Applicative/index.js");
var Data_Functor = require("../Data.Functor/index.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var Data_Unit = require("../Data.Unit/index.js");
var Effect = require("../Effect/index.js");
var Effect_Ref = require("../Effect.Ref/index.js");
var Egg_Dom_TouchEvents = require("../Egg.Dom.TouchEvents/index.js");
var Egg_Types_InputEvent = require("../Egg.Types.InputEvent/index.js");
var Web_Event_EventTarget = require("../Web.Event.EventTarget/index.js");
var Web_HTML = require("../Web.HTML/index.js");
var Web_HTML_Window = require("../Web.HTML.Window/index.js");
var Web_UIEvent_KeyboardEvent = require("../Web.UIEvent.KeyboardEvent/index.js");
var updateInputEventRef = function (ref) {
    return function (event) {
        return Effect_Ref.write(new Data_Maybe.Just(event))(ref);
    };
};
var readKeyboardEvent = function (updater) {
    return function (e) {
        var v = Data_Functor.map(Data_Maybe.functorMaybe)(Web_UIEvent_KeyboardEvent.code)(Web_UIEvent_KeyboardEvent.fromEvent(e));
        if (v instanceof Data_Maybe.Just && v.value0 === "ArrowLeft") {
            return updater(Egg_Types_InputEvent.LeftArrow.value);
        };
        if (v instanceof Data_Maybe.Just && v.value0 === "ArrowRight") {
            return updater(Egg_Types_InputEvent.RightArrow.value);
        };
        if (v instanceof Data_Maybe.Just && v.value0 === "Space") {
            return updater(Egg_Types_InputEvent.Pause.value);
        };
        if (v instanceof Data_Maybe.Just) {
            return updater(new Egg_Types_InputEvent.KeyPress(v.value0));
        };
        return Control_Applicative.pure(Effect.applicativeEffect)(Data_Unit.unit);
    };
};
var getWindowSize = function __do() {
    var v = Web_HTML.window();
    var v1 = Web_HTML_Window.innerWidth(v)();
    var v2 = Web_HTML_Window.innerHeight(v)();
    return {
        width: v1,
        height: v2
    };
};
var readResizeEvent = function (updater) {
    return function (v) {
        return function __do() {
            var v1 = getWindowSize();
            return updater(new Egg_Types_InputEvent.ResizeWindow(v1.width, v1.height))();
        };
    };
};
var getWindowEventTarget = Data_Functor.map(Effect.functorEffect)(Web_HTML_Window.toEventTarget)(Web_HTML.window);
var createWindowSizeListener = function (updater) {
    return function __do() {
        var v = Web_Event_EventTarget.eventListener(readResizeEvent(updater))();
        var v1 = getWindowEventTarget();
        return Web_Event_EventTarget.addEventListener("resize")(v)(false)(v1)();
    };
};
var createSwipeListener = function (updater) {
    var rightSwipeFn = updater(Egg_Types_InputEvent.RightArrow.value);
    var leftSwipeFn = updater(Egg_Types_InputEvent.LeftArrow.value);
    return function () {
        return Egg_Dom_TouchEvents.setupSwipes("wrapper", leftSwipeFn, rightSwipeFn);
    };
};
var createKeypressListener = function (updater) {
    return function __do() {
        var v = Web_Event_EventTarget.eventListener(readKeyboardEvent(updater))();
        var v1 = getWindowEventTarget();
        return Web_Event_EventTarget.addEventListener("keydown")(v)(false)(v1)();
    };
};
var setupEvents = function (ref) {
    var updater = updateInputEventRef(ref);
    return function __do() {
        readResizeEvent(updater)("")();
        createWindowSizeListener(updater)();
        createKeypressListener(updater)();
        return createSwipeListener(updater)();
    };
};
module.exports = {
    updateInputEventRef: updateInputEventRef,
    setupEvents: setupEvents,
    createSwipeListener: createSwipeListener,
    createKeypressListener: createKeypressListener,
    readKeyboardEvent: readKeyboardEvent,
    createWindowSizeListener: createWindowSizeListener,
    getWindowEventTarget: getWindowEventTarget,
    readResizeEvent: readResizeEvent,
    getWindowSize: getWindowSize
};
