// Generated by purs version 0.13.5
"use strict";
var Unsafe_Coerce = require("../Unsafe.Coerce/index.js");
var toEventTarget = Unsafe_Coerce.unsafeCoerce;
module.exports = {
    toEventTarget: toEventTarget
};
