// Generated by purs version 0.13.5
"use strict";
var Data_Eq = require("../Data.Eq/index.js");
var Data_Int = require("../Data.Int/index.js");
var Data_Ord = require("../Data.Ord/index.js");
var Data_Ring = require("../Data.Ring/index.js");
var Data_Semigroup = require("../Data.Semigroup/index.js");
var Data_Semiring = require("../Data.Semiring/index.js");
var Data_Show = require("../Data.Show/index.js");
var $$Math = require("../Math/index.js");
var RenderAngleRad = function (x) {
    return x;
};
var RenderAngle = function (x) {
    return x;
};
var toRadians = function (v) {
    return RenderAngleRad(Data_Int.toNumber(v) * ($$Math.pi / 180.0));
};
var showRenderAngle = Data_Show.showInt;
var semiringRenderAngle = Data_Semiring.semiringInt;
var ringRenderAngle = Data_Ring.ringInt;
var ordRenderAngle = Data_Ord.ordInt;
var invertAngle = function (v) {
    return (-1 | 0) * v | 0;
};
var increase = function (fst) {
    return function (snd) {
        var total = Data_Semiring.add(semiringRenderAngle)(fst)(snd);
        var $4 = Data_Ord.greaterThan(ordRenderAngle)(total)(359);
        if ($4) {
            return Data_Ring.sub(ringRenderAngle)(total)(360);
        };
        return total;
    };
};
var semigroupRenderAngle = new Data_Semigroup.Semigroup(increase);
var eqRenderAngle = Data_Eq.eqInt;
var decrease = function (fst) {
    return function (snd) {
        var total = Data_Ring.sub(ringRenderAngle)(fst)(snd);
        var $5 = Data_Ord.lessThan(ordRenderAngle)(total)(0);
        if ($5) {
            return Data_Semiring.add(semiringRenderAngle)(total)(360);
        };
        return total;
    };
};
module.exports = {
    RenderAngle: RenderAngle,
    RenderAngleRad: RenderAngleRad,
    toRadians: toRadians,
    invertAngle: invertAngle,
    increase: increase,
    decrease: decrease,
    eqRenderAngle: eqRenderAngle,
    ordRenderAngle: ordRenderAngle,
    showRenderAngle: showRenderAngle,
    semiringRenderAngle: semiringRenderAngle,
    ringRenderAngle: ringRenderAngle,
    semigroupRenderAngle: semigroupRenderAngle
};
