// Generated by purs version 0.13.5
"use strict";
var Data_Eq = require("../Data.Eq/index.js");
var Data_Ord = require("../Data.Ord/index.js");
var Data_Ordering = require("../Data.Ordering/index.js");
var Data_Show = require("../Data.Show/index.js");
var CurrentFrame = (function () {
    function CurrentFrame(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    CurrentFrame.create = function (value0) {
        return function (value1) {
            return new CurrentFrame(value0, value1);
        };
    };
    return CurrentFrame;
})();
var showCurrentFrame = new Data_Show.Show(function (v) {
    return "Frame " + (Data_Show.show(Data_Show.showInt)(v.value1) + (", maxiumum " + Data_Show.show(Data_Show.showInt)(v.value0)));
});
var inc = function (v) {
    var $22 = (v.value1 + 1 | 0) >= v.value0;
    if ($22) {
        return new CurrentFrame(v.value0, 0);
    };
    return new CurrentFrame(v.value0, v.value1 + 1 | 0);
};
var getCurrentFrame = function (v) {
    return v.value1;
};
var eqCurrentFrame = new Data_Eq.Eq(function (x) {
    return function (y) {
        return x.value0 === y.value0 && x.value1 === y.value1;
    };
});
var ordCurrentFrame = new Data_Ord.Ord(function () {
    return eqCurrentFrame;
}, function (x) {
    return function (y) {
        var v = Data_Ord.compare(Data_Ord.ordInt)(x.value0)(y.value0);
        if (v instanceof Data_Ordering.LT) {
            return Data_Ordering.LT.value;
        };
        if (v instanceof Data_Ordering.GT) {
            return Data_Ordering.GT.value;
        };
        return Data_Ord.compare(Data_Ord.ordInt)(x.value1)(y.value1);
    };
});
var dec = function (v) {
    var $42 = (v.value1 - 1 | 0) < 0;
    if ($42) {
        return new CurrentFrame(v.value0, v.value0 - 1 | 0);
    };
    return new CurrentFrame(v.value0, v.value1 - 1 | 0);
};
var createCurrentFrame = function (max) {
    return new CurrentFrame(max, 0);
};
module.exports = {
    createCurrentFrame: createCurrentFrame,
    inc: inc,
    dec: dec,
    getCurrentFrame: getCurrentFrame,
    eqCurrentFrame: eqCurrentFrame,
    ordCurrentFrame: ordCurrentFrame,
    showCurrentFrame: showCurrentFrame
};
