// Generated by purs version 0.13.5
"use strict";
var Data_Eq = require("../Data.Eq/index.js");
var Data_Show = require("../Data.Show/index.js");
var KeepPlaying = (function () {
    function KeepPlaying() {

    };
    KeepPlaying.value = new KeepPlaying();
    return KeepPlaying;
})();
var BackAtTheEggCup = (function () {
    function BackAtTheEggCup() {

    };
    BackAtTheEggCup.value = new BackAtTheEggCup();
    return BackAtTheEggCup;
})();
var showOutcome = new Data_Show.Show(function (v) {
    if (v instanceof KeepPlaying) {
        return "KeepPlaying";
    };
    if (v instanceof BackAtTheEggCup) {
        return "BackAtTheEggCup";
    };
    throw new Error("Failed pattern match at Egg.Types.Outcome (line 10, column 1 - line 12, column 43): " + [ v.constructor.name ]);
});
var eqOutcome = new Data_Eq.Eq(function (x) {
    return function (y) {
        if (x instanceof KeepPlaying && y instanceof KeepPlaying) {
            return true;
        };
        if (x instanceof BackAtTheEggCup && y instanceof BackAtTheEggCup) {
            return true;
        };
        return false;
    };
});
module.exports = {
    KeepPlaying: KeepPlaying,
    BackAtTheEggCup: BackAtTheEggCup,
    showOutcome: showOutcome,
    eqOutcome: eqOutcome
};
