// Generated by purs version 0.13.5
"use strict";
var Control_Bind = require("../Control.Bind/index.js");
var Data_Array = require("../Data.Array/index.js");
var Data_Eq = require("../Data.Eq/index.js");
var Data_Identity = require("../Data.Identity/index.js");
var Data_Map_Internal = require("../Data.Map.Internal/index.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var Data_Ord = require("../Data.Ord/index.js");
var Data_Show = require("../Data.Show/index.js");
var Data_Symbol = require("../Data.Symbol/index.js");
var Effect_Aff = require("../Effect.Aff/index.js");
var Egg_Data_TileSet = require("../Egg.Data.TileSet/index.js");
var Egg_Logic_InitialiseLevel = require("../Egg.Logic.InitialiseLevel/index.js");
var Egg_Logic_TakeTurn = require("../Egg.Logic.TakeTurn/index.js");
var Egg_Types_Action = require("../Egg.Types.Action/index.js");
var Egg_Types_Board = require("../Egg.Types.Board/index.js");
var Egg_Types_Coord = require("../Egg.Types.Coord/index.js");
var Egg_Types_CurrentFrame = require("../Egg.Types.CurrentFrame/index.js");
var Egg_Types_LastAction = require("../Egg.Types.LastAction/index.js");
var Egg_Types_Outcome = require("../Egg.Types.Outcome/index.js");
var Egg_Types_PlayerType = require("../Egg.Types.PlayerType/index.js");
var Egg_Types_RenderAngle = require("../Egg.Types.RenderAngle/index.js");
var Egg_Types_ResourceUrl = require("../Egg.Types.ResourceUrl/index.js");
var Egg_Types_Score = require("../Egg.Types.Score/index.js");
var Egg_Types_ScreenSize = require("../Egg.Types.ScreenSize/index.js");
var Egg_Types_TileAction = require("../Egg.Types.TileAction/index.js");
var Matrix = require("../Matrix/index.js");
var Test_Spec = require("../Test.Spec/index.js");
var Test_Spec_Assertions = require("../Test.Spec.Assertions/index.js");
var addTile = function (i) {
    return function (x) {
        return function (board) {
            var newBoard = function (ec) {
                return Matrix.set(x)(x)(ec)(board);
            };
            var eggCup = Data_Map_Internal.lookup(Data_Ord.ordInt)(i)(Egg_Data_TileSet.tiles);
            return Data_Maybe.fromMaybe(board)(Control_Bind.bind(Data_Maybe.bindMaybe)(eggCup)(newBoard));
        };
    };
};
var addOneEggCup = addTile(12);
var testGameState = (function () {
    var addOutcome = function (gs) {
        return {
            outcome: Egg_Types_Outcome.BackAtTheEggCup.value,
            board: gs.board,
            current: gs.current,
            players: gs.players,
            renderAngle: gs.renderAngle,
            rotateAngle: gs.rotateAngle,
            rotations: gs.rotations,
            score: gs.score,
            screenSize: gs.screenSize,
            turns: gs.turns
        };
    };
    return addOutcome(Egg_Logic_InitialiseLevel.initialiseGameState(addOneEggCup(1)(Egg_Types_Board.emptyBoard(10))));
})();
var addCacti = addTile(3);
var gameStateNotFinished = Egg_Logic_InitialiseLevel.initialiseGameState(addOneEggCup(2)(addOneEggCup(3)(addCacti(4)(Egg_Types_Board.emptyBoard(10)))));
var tests = Test_Spec.describe(Data_Identity.monadIdentity)("Take turn")(Test_Spec.describe(Data_Identity.monadIdentity)("doAction")(Control_Bind.discard(Control_Bind.discardUnit)(Test_Spec.bindSpecT(Data_Identity.bindIdentity))(Test_Spec.it(Data_Identity.monadIdentity)(Test_Spec.exampleMUnit)("Does nothing when Paused")(Test_Spec_Assertions.shouldEqual(Effect_Aff.monadThrowAff)(Data_Maybe.showMaybe(Data_Show.showRecord()(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "board";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "current";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "outcome";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "players";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "renderAngle";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "rotateAngle";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "rotations";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "score";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "screenSize";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "turns";
}))(Data_Show.showRecordFieldsNil)(Data_Show.showInt))(Egg_Types_ScreenSize.showScreenSize))(Egg_Types_Score.showScore))(Data_Show.showInt))(Egg_Types_RenderAngle.showRenderAngle))(Egg_Types_RenderAngle.showRenderAngle))(Data_Show.showArray(Data_Show.showRecord()(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "coords";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "currentFrame";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "direction";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "falling";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "id";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "lastAction";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "moved";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "oldDirection";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "playerType";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "stop";
}))(Data_Show.showRecordFieldsNil)(Data_Show.showBoolean))(Data_Show.showRecord()(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "fallSpeed";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "flying";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "frames";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "img";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "movePattern";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "moveSpeed";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "multiplier";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "title";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "type_";
}))(Data_Show.showRecordFieldsNil)(Egg_Types_PlayerType.showPlayerKind))(Data_Show.showString))(Data_Show.showInt))(Data_Show.showInt))(Data_Show.showString))(Egg_Types_ResourceUrl.showResourceUrl))(Data_Show.showInt))(Data_Show.showBoolean))(Data_Show.showInt))))(Egg_Types_Coord.showCoord))(Data_Show.showBoolean))(Data_Maybe.showMaybe(Egg_Types_LastAction.showLastAction)))(Data_Show.showInt))(Data_Show.showBoolean))(Egg_Types_Coord.showCoord))(Egg_Types_CurrentFrame.showCurrentFrame))(Egg_Types_Coord.showCoord)))))(Egg_Types_Outcome.showOutcome))(Egg_Types_Action.showAction))(Matrix.showMatrix(Data_Show.showRecord()(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "action";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "background";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "breakable";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "createPlayer";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "dontAdd";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "drawMe";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "frontLayer";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "id";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "img";
}))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
    return "title";
}))(Data_Show.showRecordFieldsNil)(Data_Show.showString))(Egg_Types_ResourceUrl.showResourceUrl))(Data_Show.showInt))(Data_Show.showBoolean))(Data_Show.showBoolean))(Data_Show.showBoolean))(Data_Maybe.showMaybe(Egg_Types_PlayerType.showPlayerKind)))(Data_Show.showBoolean))(Data_Show.showBoolean))(Egg_Types_TileAction.showTileAction)))))))(Data_Maybe.eqMaybe(Data_Eq.eqRec()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function () {
    return "turns";
}))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
    return "screenSize";
}))(Egg_Types_ScreenSize.eqScreenSize))()(new Data_Symbol.IsSymbol(function () {
    return "score";
}))(Egg_Types_Score.eqScore))()(new Data_Symbol.IsSymbol(function () {
    return "rotations";
}))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
    return "rotateAngle";
}))(Egg_Types_RenderAngle.eqRenderAngle))()(new Data_Symbol.IsSymbol(function () {
    return "renderAngle";
}))(Egg_Types_RenderAngle.eqRenderAngle))()(new Data_Symbol.IsSymbol(function () {
    return "players";
}))(Data_Eq.eqArray(Data_Eq.eqRec()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function () {
    return "stop";
}))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
    return "playerType";
}))(Data_Eq.eqRec()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function () {
    return "type_";
}))(Egg_Types_PlayerType.eqPlayerKind))()(new Data_Symbol.IsSymbol(function () {
    return "title";
}))(Data_Eq.eqString))()(new Data_Symbol.IsSymbol(function () {
    return "multiplier";
}))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
    return "moveSpeed";
}))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
    return "movePattern";
}))(Data_Eq.eqString))()(new Data_Symbol.IsSymbol(function () {
    return "img";
}))(Egg_Types_ResourceUrl.eqResourceUrl))()(new Data_Symbol.IsSymbol(function () {
    return "frames";
}))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
    return "flying";
}))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
    return "fallSpeed";
}))(Data_Eq.eqInt))))()(new Data_Symbol.IsSymbol(function () {
    return "oldDirection";
}))(Egg_Types_Coord.eqCoord))()(new Data_Symbol.IsSymbol(function () {
    return "moved";
}))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
    return "lastAction";
}))(Data_Maybe.eqMaybe(Egg_Types_LastAction.eqLastAction)))()(new Data_Symbol.IsSymbol(function () {
    return "id";
}))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
    return "falling";
}))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
    return "direction";
}))(Egg_Types_Coord.eqCoord))()(new Data_Symbol.IsSymbol(function () {
    return "currentFrame";
}))(Egg_Types_CurrentFrame.eqCurrentFrame))()(new Data_Symbol.IsSymbol(function () {
    return "coords";
}))(Egg_Types_Coord.eqCoord)))))()(new Data_Symbol.IsSymbol(function () {
    return "outcome";
}))(Egg_Types_Outcome.eqOutcome))()(new Data_Symbol.IsSymbol(function () {
    return "current";
}))(Egg_Types_Action.eqAction))()(new Data_Symbol.IsSymbol(function () {
    return "board";
}))(Matrix.eqMatrix(Data_Eq.eqRec()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function () {
    return "title";
}))(Data_Eq.eqString))()(new Data_Symbol.IsSymbol(function () {
    return "img";
}))(Egg_Types_ResourceUrl.eqResourceUrl))()(new Data_Symbol.IsSymbol(function () {
    return "id";
}))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
    return "frontLayer";
}))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
    return "drawMe";
}))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
    return "dontAdd";
}))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
    return "createPlayer";
}))(Data_Maybe.eqMaybe(Egg_Types_PlayerType.eqPlayerKind)))()(new Data_Symbol.IsSymbol(function () {
    return "breakable";
}))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
    return "background";
}))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
    return "action";
}))(Egg_Types_TileAction.eqTileAction)))))))(Egg_Logic_TakeTurn.doAction(testGameState)(Egg_Types_Action.Paused.value)(1000))(new Data_Maybe.Just(testGameState))))(function () {
    return Control_Bind.discard(Control_Bind.discardUnit)(Test_Spec.bindSpecT(Data_Identity.bindIdentity))(Test_Spec.it(Data_Identity.monadIdentity)(Test_Spec.exampleMUnit)("Does nothing when interval is under 1")(Test_Spec_Assertions.shouldEqual(Effect_Aff.monadThrowAff)(Data_Maybe.showMaybe(Data_Show.showRecord()(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "board";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "current";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "outcome";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "players";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "renderAngle";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "rotateAngle";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "rotations";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "score";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "screenSize";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "turns";
    }))(Data_Show.showRecordFieldsNil)(Data_Show.showInt))(Egg_Types_ScreenSize.showScreenSize))(Egg_Types_Score.showScore))(Data_Show.showInt))(Egg_Types_RenderAngle.showRenderAngle))(Egg_Types_RenderAngle.showRenderAngle))(Data_Show.showArray(Data_Show.showRecord()(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "coords";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "currentFrame";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "direction";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "falling";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "id";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "lastAction";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "moved";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "oldDirection";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "playerType";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "stop";
    }))(Data_Show.showRecordFieldsNil)(Data_Show.showBoolean))(Data_Show.showRecord()(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "fallSpeed";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "flying";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "frames";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "img";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "movePattern";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "moveSpeed";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "multiplier";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "title";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "type_";
    }))(Data_Show.showRecordFieldsNil)(Egg_Types_PlayerType.showPlayerKind))(Data_Show.showString))(Data_Show.showInt))(Data_Show.showInt))(Data_Show.showString))(Egg_Types_ResourceUrl.showResourceUrl))(Data_Show.showInt))(Data_Show.showBoolean))(Data_Show.showInt))))(Egg_Types_Coord.showCoord))(Data_Show.showBoolean))(Data_Maybe.showMaybe(Egg_Types_LastAction.showLastAction)))(Data_Show.showInt))(Data_Show.showBoolean))(Egg_Types_Coord.showCoord))(Egg_Types_CurrentFrame.showCurrentFrame))(Egg_Types_Coord.showCoord)))))(Egg_Types_Outcome.showOutcome))(Egg_Types_Action.showAction))(Matrix.showMatrix(Data_Show.showRecord()(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "action";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "background";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "breakable";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "createPlayer";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "dontAdd";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "drawMe";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "frontLayer";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "id";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "img";
    }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
        return "title";
    }))(Data_Show.showRecordFieldsNil)(Data_Show.showString))(Egg_Types_ResourceUrl.showResourceUrl))(Data_Show.showInt))(Data_Show.showBoolean))(Data_Show.showBoolean))(Data_Show.showBoolean))(Data_Maybe.showMaybe(Egg_Types_PlayerType.showPlayerKind)))(Data_Show.showBoolean))(Data_Show.showBoolean))(Egg_Types_TileAction.showTileAction)))))))(Data_Maybe.eqMaybe(Data_Eq.eqRec()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function () {
        return "turns";
    }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
        return "screenSize";
    }))(Egg_Types_ScreenSize.eqScreenSize))()(new Data_Symbol.IsSymbol(function () {
        return "score";
    }))(Egg_Types_Score.eqScore))()(new Data_Symbol.IsSymbol(function () {
        return "rotations";
    }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
        return "rotateAngle";
    }))(Egg_Types_RenderAngle.eqRenderAngle))()(new Data_Symbol.IsSymbol(function () {
        return "renderAngle";
    }))(Egg_Types_RenderAngle.eqRenderAngle))()(new Data_Symbol.IsSymbol(function () {
        return "players";
    }))(Data_Eq.eqArray(Data_Eq.eqRec()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function () {
        return "stop";
    }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
        return "playerType";
    }))(Data_Eq.eqRec()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function () {
        return "type_";
    }))(Egg_Types_PlayerType.eqPlayerKind))()(new Data_Symbol.IsSymbol(function () {
        return "title";
    }))(Data_Eq.eqString))()(new Data_Symbol.IsSymbol(function () {
        return "multiplier";
    }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
        return "moveSpeed";
    }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
        return "movePattern";
    }))(Data_Eq.eqString))()(new Data_Symbol.IsSymbol(function () {
        return "img";
    }))(Egg_Types_ResourceUrl.eqResourceUrl))()(new Data_Symbol.IsSymbol(function () {
        return "frames";
    }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
        return "flying";
    }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
        return "fallSpeed";
    }))(Data_Eq.eqInt))))()(new Data_Symbol.IsSymbol(function () {
        return "oldDirection";
    }))(Egg_Types_Coord.eqCoord))()(new Data_Symbol.IsSymbol(function () {
        return "moved";
    }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
        return "lastAction";
    }))(Data_Maybe.eqMaybe(Egg_Types_LastAction.eqLastAction)))()(new Data_Symbol.IsSymbol(function () {
        return "id";
    }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
        return "falling";
    }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
        return "direction";
    }))(Egg_Types_Coord.eqCoord))()(new Data_Symbol.IsSymbol(function () {
        return "currentFrame";
    }))(Egg_Types_CurrentFrame.eqCurrentFrame))()(new Data_Symbol.IsSymbol(function () {
        return "coords";
    }))(Egg_Types_Coord.eqCoord)))))()(new Data_Symbol.IsSymbol(function () {
        return "outcome";
    }))(Egg_Types_Outcome.eqOutcome))()(new Data_Symbol.IsSymbol(function () {
        return "current";
    }))(Egg_Types_Action.eqAction))()(new Data_Symbol.IsSymbol(function () {
        return "board";
    }))(Matrix.eqMatrix(Data_Eq.eqRec()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function () {
        return "title";
    }))(Data_Eq.eqString))()(new Data_Symbol.IsSymbol(function () {
        return "img";
    }))(Egg_Types_ResourceUrl.eqResourceUrl))()(new Data_Symbol.IsSymbol(function () {
        return "id";
    }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
        return "frontLayer";
    }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
        return "drawMe";
    }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
        return "dontAdd";
    }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
        return "createPlayer";
    }))(Data_Maybe.eqMaybe(Egg_Types_PlayerType.eqPlayerKind)))()(new Data_Symbol.IsSymbol(function () {
        return "breakable";
    }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
        return "background";
    }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
        return "action";
    }))(Egg_Types_TileAction.eqTileAction)))))))(Egg_Logic_TakeTurn.doAction(testGameState)(Egg_Types_Action.Playing.value)(0))(new Data_Maybe.Just(testGameState))))(function () {
        return Control_Bind.discard(Control_Bind.discardUnit)(Test_Spec.bindSpecT(Data_Identity.bindIdentity))(Test_Spec.it(Data_Identity.monadIdentity)(Test_Spec.exampleMUnit)("Increments turn count when Playing with interval over 0")(Test_Spec_Assertions.shouldNotEqual(Effect_Aff.monadThrowAff)(Data_Maybe.showMaybe(Data_Show.showRecord()(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "board";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "current";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "outcome";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "players";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "renderAngle";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "rotateAngle";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "rotations";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "score";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "screenSize";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "turns";
        }))(Data_Show.showRecordFieldsNil)(Data_Show.showInt))(Egg_Types_ScreenSize.showScreenSize))(Egg_Types_Score.showScore))(Data_Show.showInt))(Egg_Types_RenderAngle.showRenderAngle))(Egg_Types_RenderAngle.showRenderAngle))(Data_Show.showArray(Data_Show.showRecord()(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "coords";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "currentFrame";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "direction";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "falling";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "id";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "lastAction";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "moved";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "oldDirection";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "playerType";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "stop";
        }))(Data_Show.showRecordFieldsNil)(Data_Show.showBoolean))(Data_Show.showRecord()(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "fallSpeed";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "flying";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "frames";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "img";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "movePattern";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "moveSpeed";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "multiplier";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "title";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "type_";
        }))(Data_Show.showRecordFieldsNil)(Egg_Types_PlayerType.showPlayerKind))(Data_Show.showString))(Data_Show.showInt))(Data_Show.showInt))(Data_Show.showString))(Egg_Types_ResourceUrl.showResourceUrl))(Data_Show.showInt))(Data_Show.showBoolean))(Data_Show.showInt))))(Egg_Types_Coord.showCoord))(Data_Show.showBoolean))(Data_Maybe.showMaybe(Egg_Types_LastAction.showLastAction)))(Data_Show.showInt))(Data_Show.showBoolean))(Egg_Types_Coord.showCoord))(Egg_Types_CurrentFrame.showCurrentFrame))(Egg_Types_Coord.showCoord)))))(Egg_Types_Outcome.showOutcome))(Egg_Types_Action.showAction))(Matrix.showMatrix(Data_Show.showRecord()(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "action";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "background";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "breakable";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "createPlayer";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "dontAdd";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "drawMe";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "frontLayer";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "id";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "img";
        }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
            return "title";
        }))(Data_Show.showRecordFieldsNil)(Data_Show.showString))(Egg_Types_ResourceUrl.showResourceUrl))(Data_Show.showInt))(Data_Show.showBoolean))(Data_Show.showBoolean))(Data_Show.showBoolean))(Data_Maybe.showMaybe(Egg_Types_PlayerType.showPlayerKind)))(Data_Show.showBoolean))(Data_Show.showBoolean))(Egg_Types_TileAction.showTileAction)))))))(Data_Maybe.eqMaybe(Data_Eq.eqRec()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function () {
            return "turns";
        }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
            return "screenSize";
        }))(Egg_Types_ScreenSize.eqScreenSize))()(new Data_Symbol.IsSymbol(function () {
            return "score";
        }))(Egg_Types_Score.eqScore))()(new Data_Symbol.IsSymbol(function () {
            return "rotations";
        }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
            return "rotateAngle";
        }))(Egg_Types_RenderAngle.eqRenderAngle))()(new Data_Symbol.IsSymbol(function () {
            return "renderAngle";
        }))(Egg_Types_RenderAngle.eqRenderAngle))()(new Data_Symbol.IsSymbol(function () {
            return "players";
        }))(Data_Eq.eqArray(Data_Eq.eqRec()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function () {
            return "stop";
        }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
            return "playerType";
        }))(Data_Eq.eqRec()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function () {
            return "type_";
        }))(Egg_Types_PlayerType.eqPlayerKind))()(new Data_Symbol.IsSymbol(function () {
            return "title";
        }))(Data_Eq.eqString))()(new Data_Symbol.IsSymbol(function () {
            return "multiplier";
        }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
            return "moveSpeed";
        }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
            return "movePattern";
        }))(Data_Eq.eqString))()(new Data_Symbol.IsSymbol(function () {
            return "img";
        }))(Egg_Types_ResourceUrl.eqResourceUrl))()(new Data_Symbol.IsSymbol(function () {
            return "frames";
        }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
            return "flying";
        }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
            return "fallSpeed";
        }))(Data_Eq.eqInt))))()(new Data_Symbol.IsSymbol(function () {
            return "oldDirection";
        }))(Egg_Types_Coord.eqCoord))()(new Data_Symbol.IsSymbol(function () {
            return "moved";
        }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
            return "lastAction";
        }))(Data_Maybe.eqMaybe(Egg_Types_LastAction.eqLastAction)))()(new Data_Symbol.IsSymbol(function () {
            return "id";
        }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
            return "falling";
        }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
            return "direction";
        }))(Egg_Types_Coord.eqCoord))()(new Data_Symbol.IsSymbol(function () {
            return "currentFrame";
        }))(Egg_Types_CurrentFrame.eqCurrentFrame))()(new Data_Symbol.IsSymbol(function () {
            return "coords";
        }))(Egg_Types_Coord.eqCoord)))))()(new Data_Symbol.IsSymbol(function () {
            return "outcome";
        }))(Egg_Types_Outcome.eqOutcome))()(new Data_Symbol.IsSymbol(function () {
            return "current";
        }))(Egg_Types_Action.eqAction))()(new Data_Symbol.IsSymbol(function () {
            return "board";
        }))(Matrix.eqMatrix(Data_Eq.eqRec()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function () {
            return "title";
        }))(Data_Eq.eqString))()(new Data_Symbol.IsSymbol(function () {
            return "img";
        }))(Egg_Types_ResourceUrl.eqResourceUrl))()(new Data_Symbol.IsSymbol(function () {
            return "id";
        }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
            return "frontLayer";
        }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
            return "drawMe";
        }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
            return "dontAdd";
        }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
            return "createPlayer";
        }))(Data_Maybe.eqMaybe(Egg_Types_PlayerType.eqPlayerKind)))()(new Data_Symbol.IsSymbol(function () {
            return "breakable";
        }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
            return "background";
        }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
            return "action";
        }))(Egg_Types_TileAction.eqTileAction)))))))(Egg_Logic_TakeTurn.doAction(testGameState)(Egg_Types_Action.Playing.value)(1000))(new Data_Maybe.Just(testGameState))))(function () {
            return Control_Bind.discard(Control_Bind.discardUnit)(Test_Spec.bindSpecT(Data_Identity.bindIdentity))(Test_Spec.it(Data_Identity.monadIdentity)(Test_Spec.exampleMUnit)("Does not change into rainbow egg when there are points to get")((function () {
                var newGameState = Egg_Logic_TakeTurn.checkNearlyFinished(gameStateNotFinished);
                return Test_Spec_Assertions.shouldEqual(Effect_Aff.monadThrowAff)(Data_Show.showArray(Data_Show.showRecord()(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "coords";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "currentFrame";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "direction";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "falling";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "id";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "lastAction";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "moved";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "oldDirection";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "playerType";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "stop";
                }))(Data_Show.showRecordFieldsNil)(Data_Show.showBoolean))(Data_Show.showRecord()(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "fallSpeed";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "flying";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "frames";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "img";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "movePattern";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "moveSpeed";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "multiplier";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "title";
                }))(Data_Show.showRecordFieldsCons(new Data_Symbol.IsSymbol(function () {
                    return "type_";
                }))(Data_Show.showRecordFieldsNil)(Egg_Types_PlayerType.showPlayerKind))(Data_Show.showString))(Data_Show.showInt))(Data_Show.showInt))(Data_Show.showString))(Egg_Types_ResourceUrl.showResourceUrl))(Data_Show.showInt))(Data_Show.showBoolean))(Data_Show.showInt))))(Egg_Types_Coord.showCoord))(Data_Show.showBoolean))(Data_Maybe.showMaybe(Egg_Types_LastAction.showLastAction)))(Data_Show.showInt))(Data_Show.showBoolean))(Egg_Types_Coord.showCoord))(Egg_Types_CurrentFrame.showCurrentFrame))(Egg_Types_Coord.showCoord))))(Data_Eq.eqArray(Data_Eq.eqRec()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function () {
                    return "stop";
                }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
                    return "playerType";
                }))(Data_Eq.eqRec()(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowCons(Data_Eq.eqRowNil)()(new Data_Symbol.IsSymbol(function () {
                    return "type_";
                }))(Egg_Types_PlayerType.eqPlayerKind))()(new Data_Symbol.IsSymbol(function () {
                    return "title";
                }))(Data_Eq.eqString))()(new Data_Symbol.IsSymbol(function () {
                    return "multiplier";
                }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
                    return "moveSpeed";
                }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
                    return "movePattern";
                }))(Data_Eq.eqString))()(new Data_Symbol.IsSymbol(function () {
                    return "img";
                }))(Egg_Types_ResourceUrl.eqResourceUrl))()(new Data_Symbol.IsSymbol(function () {
                    return "frames";
                }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
                    return "flying";
                }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
                    return "fallSpeed";
                }))(Data_Eq.eqInt))))()(new Data_Symbol.IsSymbol(function () {
                    return "oldDirection";
                }))(Egg_Types_Coord.eqCoord))()(new Data_Symbol.IsSymbol(function () {
                    return "moved";
                }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
                    return "lastAction";
                }))(Data_Maybe.eqMaybe(Egg_Types_LastAction.eqLastAction)))()(new Data_Symbol.IsSymbol(function () {
                    return "id";
                }))(Data_Eq.eqInt))()(new Data_Symbol.IsSymbol(function () {
                    return "falling";
                }))(Data_Eq.eqBoolean))()(new Data_Symbol.IsSymbol(function () {
                    return "direction";
                }))(Egg_Types_Coord.eqCoord))()(new Data_Symbol.IsSymbol(function () {
                    return "currentFrame";
                }))(Egg_Types_CurrentFrame.eqCurrentFrame))()(new Data_Symbol.IsSymbol(function () {
                    return "coords";
                }))(Egg_Types_Coord.eqCoord))))(newGameState.players)(gameStateNotFinished.players);
            })()))(function () {
                return Test_Spec.it(Data_Identity.monadIdentity)(Test_Spec.exampleMUnit)("Should change egg into rainbow egg when there are no points left")((function () {
                    var newGameState = Egg_Logic_TakeTurn.checkNearlyFinished(testGameState);
                    return Control_Bind.discard(Control_Bind.discardUnit)(Effect_Aff.bindAff)(Test_Spec_Assertions.shouldEqual(Effect_Aff.monadThrowAff)(Data_Show.showInt)(Data_Eq.eqInt)(Data_Array.length(newGameState.players))(1))(function () {
                        var newPlayer = Data_Maybe.fromJust()(Data_Array.head(newGameState.players));
                        return Test_Spec_Assertions.shouldEqual(Effect_Aff.monadThrowAff)(Egg_Types_PlayerType.showPlayerKind)(Egg_Types_PlayerType.eqPlayerKind)(newPlayer.playerType.type_)(Egg_Types_PlayerType.RainbowEgg.value);
                    });
                })());
            });
        });
    });
})));
module.exports = {
    addTile: addTile,
    addOneEggCup: addOneEggCup,
    addCacti: addCacti,
    testGameState: testGameState,
    gameStateNotFinished: gameStateNotFinished,
    tests: tests
};
