// Generated by purs version 0.13.5
"use strict";
var Data_Maybe = require("../Data.Maybe/index.js");
var Egg_Types_ResourceUrl = require("../Egg.Types.ResourceUrl/index.js");
var Egg_Types_TileAction = require("../Egg.Types.TileAction/index.js");
var tileSize = 64;
var defaultTile = {
    action: Egg_Types_TileAction.NoOp.value,
    drawMe: true,
    background: false,
    breakable: false,
    createPlayer: Data_Maybe.Nothing.value,
    dontAdd: false,
    frontLayer: false,
    id: 0,
    img: new Egg_Types_ResourceUrl.TileResource("sky"),
    title: "Title"
};
var emptyTile = {
    id: 1,
    title: "Title",
    img: new Egg_Types_ResourceUrl.TileResource("sky"),
    drawMe: false,
    background: true,
    frontLayer: defaultTile.frontLayer,
    breakable: defaultTile.breakable,
    action: defaultTile.action,
    dontAdd: defaultTile.dontAdd,
    createPlayer: defaultTile.createPlayer
};
module.exports = {
    tileSize: tileSize,
    emptyTile: emptyTile,
    defaultTile: defaultTile
};
