// Generated by purs version 0.13.5
"use strict";
var Data_Maybe = require("../Data.Maybe/index.js");
var Matrix = require("../Matrix/index.js");
var getMapSize = function (pathMap) {
    return {
        width: Matrix.width(pathMap),
        height: Matrix.height(pathMap)
    };
};
var createEmpty = function (i) {
    return Matrix.repeat(i)(i)(true);
};
var checkSquare = function (pathMap) {
    return function (v) {
        return Data_Maybe.fromMaybe(false)(Matrix.get(v.value0)(v.value1)(pathMap));
    };
};
module.exports = {
    getMapSize: getMapSize,
    checkSquare: checkSquare,
    createEmpty: createEmpty
};
