// Generated by purs version 0.13.5
"use strict";
var Control_Bind = require("../Control.Bind/index.js");
var Data_Identity = require("../Data.Identity/index.js");
var Effect_Aff = require("../Effect.Aff/index.js");
var Test_Logic_Action = require("../Test.Logic.Action/index.js");
var Test_Logic_Collisions = require("../Test.Logic.Collisions/index.js");
var Test_Logic_LoadLevel = require("../Test.Logic.LoadLevel/index.js");
var Test_Logic_Map = require("../Test.Logic.Map/index.js");
var Test_Logic_Movement = require("../Test.Logic.Movement/index.js");
var Test_Logic_PathFinder = require("../Test.Logic.PathFinder/index.js");
var Test_Logic_RenderMap = require("../Test.Logic.RenderMap/index.js");
var Test_Logic_TakeTurn = require("../Test.Logic.TakeTurn/index.js");
var Test_Spec = require("../Test.Spec/index.js");
var Test_Spec_Reporter_Console = require("../Test.Spec.Reporter.Console/index.js");
var Test_Spec_Runner = require("../Test.Spec.Runner/index.js");
var main = Effect_Aff.launchAff_(Test_Spec_Runner.runSpec([ Test_Spec_Reporter_Console.consoleReporter ])(Control_Bind.discard(Control_Bind.discardUnit)(Test_Spec.bindSpecT(Data_Identity.bindIdentity))(Test_Logic_TakeTurn.tests)(function () {
    return Control_Bind.discard(Control_Bind.discardUnit)(Test_Spec.bindSpecT(Data_Identity.bindIdentity))(Test_Logic_Movement.tests)(function () {
        return Control_Bind.discard(Control_Bind.discardUnit)(Test_Spec.bindSpecT(Data_Identity.bindIdentity))(Test_Logic_Action.tests)(function () {
            return Control_Bind.discard(Control_Bind.discardUnit)(Test_Spec.bindSpecT(Data_Identity.bindIdentity))(Test_Logic_Map.tests)(function () {
                return Control_Bind.discard(Control_Bind.discardUnit)(Test_Spec.bindSpecT(Data_Identity.bindIdentity))(Test_Logic_RenderMap.tests)(function () {
                    return Control_Bind.discard(Control_Bind.discardUnit)(Test_Spec.bindSpecT(Data_Identity.bindIdentity))(Test_Logic_LoadLevel.tests)(function () {
                        return Control_Bind.discard(Control_Bind.discardUnit)(Test_Spec.bindSpecT(Data_Identity.bindIdentity))(Test_Logic_Collisions.tests)(function () {
                            return Test_Logic_PathFinder.tests;
                        });
                    });
                });
            });
        });
    });
})));
module.exports = {
    main: main
};
