// Generated by purs version 0.13.5
"use strict";
var Data_Eq = require("../Data.Eq/index.js");
var Data_Ord = require("../Data.Ord/index.js");
var Data_Ordering = require("../Data.Ordering/index.js");
var Data_Show = require("../Data.Show/index.js");
var TileResource = (function () {
    function TileResource(value0) {
        this.value0 = value0;
    };
    TileResource.create = function (value0) {
        return new TileResource(value0);
    };
    return TileResource;
})();
var SpriteResource = (function () {
    function SpriteResource(value0) {
        this.value0 = value0;
    };
    SpriteResource.create = function (value0) {
        return new SpriteResource(value0);
    };
    return SpriteResource;
})();
var LevelResource = (function () {
    function LevelResource(value0) {
        this.value0 = value0;
    };
    LevelResource.create = function (value0) {
        return new LevelResource(value0);
    };
    return LevelResource;
})();
var showResourceUrl = new Data_Show.Show(function (v) {
    if (v instanceof TileResource) {
        return "/img/tiles/" + (v.value0 + ".png");
    };
    if (v instanceof SpriteResource) {
        return "/img/sprites/" + (v.value0 + ".png");
    };
    if (v instanceof LevelResource) {
        return "/levels/" + (Data_Show.show(Data_Show.showInt)(v.value0) + ".json");
    };
    throw new Error("Failed pattern match at Egg.Types.ResourceUrl (line 19, column 1 - line 22, column 65): " + [ v.constructor.name ]);
});
var eqResourceUrl = new Data_Eq.Eq(function (x) {
    return function (y) {
        if (x instanceof TileResource && y instanceof TileResource) {
            return x.value0 === y.value0;
        };
        if (x instanceof SpriteResource && y instanceof SpriteResource) {
            return x.value0 === y.value0;
        };
        if (x instanceof LevelResource && y instanceof LevelResource) {
            return x.value0 === y.value0;
        };
        return false;
    };
});
var ordResourceUrl = new Data_Ord.Ord(function () {
    return eqResourceUrl;
}, function (x) {
    return function (y) {
        if (x instanceof TileResource && y instanceof TileResource) {
            return Data_Ord.compare(Data_Ord.ordString)(x.value0)(y.value0);
        };
        if (x instanceof TileResource) {
            return Data_Ordering.LT.value;
        };
        if (y instanceof TileResource) {
            return Data_Ordering.GT.value;
        };
        if (x instanceof SpriteResource && y instanceof SpriteResource) {
            return Data_Ord.compare(Data_Ord.ordString)(x.value0)(y.value0);
        };
        if (x instanceof SpriteResource) {
            return Data_Ordering.LT.value;
        };
        if (y instanceof SpriteResource) {
            return Data_Ordering.GT.value;
        };
        if (x instanceof LevelResource && y instanceof LevelResource) {
            return Data_Ord.compare(Data_Ord.ordInt)(x.value0)(y.value0);
        };
        throw new Error("Failed pattern match at Egg.Types.ResourceUrl (line 17, column 1 - line 17, column 50): " + [ x.constructor.name, y.constructor.name ]);
    };
});
module.exports = {
    TileResource: TileResource,
    SpriteResource: SpriteResource,
    LevelResource: LevelResource,
    eqResourceUrl: eqResourceUrl,
    ordResourceUrl: ordResourceUrl,
    showResourceUrl: showResourceUrl
};
