// Generated by purs version 0.13.5
"use strict";
var Egg_Types_Action = require("../Egg.Types.Action/index.js");
var Egg_Types_Outcome = require("../Egg.Types.Outcome/index.js");
var Egg_Types_ScreenSize = require("../Egg.Types.ScreenSize/index.js");
var createGameState = function (board) {
    return {
        players: [  ],
        board: board,
        score: 0,
        rotations: 0,
        rotateAngle: 0,
        renderAngle: 0,
        outcome: Egg_Types_Outcome.KeepPlaying.value,
        turns: 0,
        current: Egg_Types_Action.Playing.value,
        screenSize: Egg_Types_ScreenSize.screenSize(1)(1)
    };
};
module.exports = {
    createGameState: createGameState
};
