// Generated by purs version 0.13.5
"use strict";
var unload = "unload";
var select = "select";
var load = "load";
var error = "error";
var abort = "abort";
module.exports = {
    load: load,
    unload: unload,
    abort: abort,
    error: error,
    select: select
};
