name: Test and build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install NPM deps
      run: yarn
    - name: Purescript tests
      run: yarn test
    - name: Webpack build
      run: yarn webpack
